### ISSUE TITLE
Invalid layer name: module.densenet121.features.denseblock4.denselayer16.conv.2

### ISSUE THREAD

**Issue by rajdeinno** [thtang/CheXNet-with-localization#8]
Hi,

I got the below error while running **denseNet_localization.py** file. 

```
Traceback (most recent call last):
  File "/media/administrator/D/XRay/CheXnet_Demo/denseNet_localization.py", line 227, in <module>
    output = gcam.generate(target_layer="module.densenet121.features.denseblock4.denselayer16.conv.2")
  File "/media/administrator/D/XRay/CheXnet_Demo/denseNet_localization.py", line 186, in generate
    fmaps = self._find(self.all_fmaps, target_layer)
  File "/media/administrator/D/XRay/CheXnet_Demo/denseNet_localization.py", line 174, in _find
    raise ValueError('Invalid layer name: {}'.format(target_layer))
ValueError: Invalid layer name: module.densenet121.features.denseblock4.denselayer16.conv.2
```

any help would be really appriciated.. Thanks in advance..

**Comment by thtang** [comment]
Do you use Pytorch==0.2.0 and torchvision==0.2.0 ?

**Comment by rajdeinno** [comment]
I am using the below version since I had some problem with torchvusion 0.2.0.

torch==1.1.0
torchvision==0.2.2

**Comment by rajdeinno** [comment]
I have updated my comments in github. Please have a look and share your opinion..

Thanks in advance

**Comment by rajdeinno** [comment]
If I use torchvision 0.2.0 and torch==1.0.1 I get the following error.

```
warn("The default mode, 'constant', will be changed to 'reflect' in "
0
Traceback (most recent call last):
  File "denseNet_localization.py", line 76, in <module>
    model = DenseNet121(8).cuda()
  File "denseNet_localization.py", line 65, in __init__
    self.densenet121 = torchvision.models.densenet121(pretrained=True)
  File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 26, in densenet121
    **kwargs)
  File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 142, in __init__
    bn_size=bn_size, growth_rate=growth_rate, drop_rate=drop_rate)
  File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 98, in __init__
    layer = _DenseLayer(num_input_features + i * growth_rate, growth_rate, bn_size, drop_rate)
  File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 77, in __init__
    self.add_module('norm.1', nn.BatchNorm2d(num_input_features)),
  File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torch/nn/modules/module.py", line 180, in add_module
    raise KeyError("module name can't contain \".\"")
KeyError: 'module name can\'t contain "."'

```

So I have upgraded torchvision to 0.2.2. and torch==1.1.0.

In this case I got the above error.

**Comment by thtang** [comment]
It seem that the errors are just caused by the different version of packages.

**Comment by rajdeinno** [comment]
It worked for me after I changed the name **module.densenet121.features.denseblock4.denselayer16.conv.2** to **module.densenet121.features.denseblock4.denselayer16.conv2**

And I had some package version issues as well.

**Comment by rajdeinno** [comment]
Hi Tang,

I am able to generate the bound_box.txt file after I execute the denseNet_localization.pyfile.
how to visualize the bound box text file into the input image? as you mentioned in ground-truth label (red) and its prediction (blue).
Thanks in advance..

Please assist me on this..

**Comment by mochita314** [comment]
I changed
module.densenet121.features.denseblock4.denselayer16.conv.2 to module.densenet121.features.denseblock4.denselayer16.conv2
but  still have same problem.
What should I do ... ??

I'm using 
torch (1.0.1.post2)
torchvision (0.2.2.post3)

```Traceback (most recent call last):
  File "denseNet_localization.py", line 247, in <module>
    output = gcam.generate(target_layer="module.densenet121.features.denseblock4.denselayer16.conv2")
  File "denseNet_localization.py", line 211, in generate
    fmaps = self._find(self.all_fmaps, target_layer)
  File "denseNet_localization.py", line 199, in _find
    raise ValueError('Invalid layer name: {}'.format(target_layer))
ValueError: Invalid layer name: module.densenet121.features.denseblock4.denselayer16.conv2```

**Comment by sp7414** [comment]
> I changed
> module.densenet121.features.denseblock4.denselayer16.conv.2 to module.densenet121.features.denseblock4.denselayer16.conv2
> but still have same problem.
> What should I do ... ??
> 
> I'm using
> torch (1.0.1.post2)
> torchvision (0.2.2.post3)
> 
> ```
>   File "denseNet_localization.py", line 247, in <module>
>     output = gcam.generate(target_layer="module.densenet121.features.denseblock4.denselayer16.conv2")
>   File "denseNet_localization.py", line 211, in generate
>     fmaps = self._find(self.all_fmaps, target_layer)
>   File "denseNet_localization.py", line 199, in _find
>     raise ValueError('Invalid layer name: {}'.format(target_layer))
> ValueError: Invalid layer name: module.densenet121.features.denseblock4.denselayer16.conv2```
> ```

have you solved this problem? I'm facing the same issue.

**Comment by ankitdata** [comment]
> > I changed
> > module.densenet121.features.denseblock4.denselayer16.conv.2 to module.densenet121.features.denseblock4.denselayer16.conv2
> > but still have same problem.
> > What should I do ... ??
> > I'm using
> > torch (1.0.1.post2)
> > torchvision (0.2.2.post3)
> > ```
> >   File "denseNet_localization.py", line 247, in <module>
> >     output = gcam.generate(target_layer="module.densenet121.features.denseblock4.denselayer16.conv2")
> >   File "denseNet_localization.py", line 211, in generate
> >     fmaps = self._find(self.all_fmaps, target_layer)
> >   File "denseNet_localization.py", line 199, in _find
> >     raise ValueError('Invalid layer name: {}'.format(target_layer))
> > ValueError: Invalid layer name: module.densenet121.features.denseblock4.denselayer16.conv2```
> > ```
> 
> have you solved this problem? I'm facing the same issue.

[see this issue might helpfull](https://github.com/thtang/CheXNet-with-localization/issues/7)

**Comment by Aliktk** [comment]
> If I use torchvision 0.2.0 and torch==1.0.1 I get the following error.
> 
> ```
> warn("The default mode, 'constant', will be changed to 'reflect' in "
> 0
> Traceback (most recent call last):
>   File "denseNet_localization.py", line 76, in <module>
>     model = DenseNet121(8).cuda()
>   File "denseNet_localization.py", line 65, in __init__
>     self.densenet121 = torchvision.models.densenet121(pretrained=True)
>   File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 26, in densenet121
>     **kwargs)
>   File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 142, in __init__
>     bn_size=bn_size, growth_rate=growth_rate, drop_rate=drop_rate)
>   File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 98, in __init__
>     layer = _DenseLayer(num_input_features + i * growth_rate, growth_rate, bn_size, drop_rate)
>   File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 77, in __init__
>     self.add_module('norm.1', nn.BatchNorm2d(num_input_features)),
>   File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torch/nn/modules/module.py", line 180, in add_module
>     raise KeyError("module name can't contain \".\"")
> KeyError: 'module name can\'t contain "."'
> ```
> 
> So I have upgraded torchvision to 0.2.2. and torch==1.1.0. and my train went successful. When I try to run **denseNet_localization.py** file then I got the above error.

Hello @rajdeinno  how did u solve this error please healp me in this regard.
Thanks @rajdeinno

**Comment by ankitdata** [comment]
> > If I use torchvision 0.2.0 and torch==1.0.1 I get the following error.
> > ```
> > warn("The default mode, 'constant', will be changed to 'reflect' in "
> > 0
> > Traceback (most recent call last):
> >   File "denseNet_localization.py", line 76, in <module>
> >     model = DenseNet121(8).cuda()
> >   File "denseNet_localization.py", line 65, in __init__
> >     self.densenet121 = torchvision.models.densenet121(pretrained=True)
> >   File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 26, in densenet121
> >     **kwargs)
> >   File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 142, in __init__
> >     bn_size=bn_size, growth_rate=growth_rate, drop_rate=drop_rate)
> >   File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 98, in __init__
> >     layer = _DenseLayer(num_input_features + i * growth_rate, growth_rate, bn_size, drop_rate)
> >   File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torchvision/models/densenet.py", line 77, in __init__
> >     self.add_module('norm.1', nn.BatchNorm2d(num_input_features)),
> >   File "/home/administrator/Desktop/Projects/xray/chexnet/setup3.5/lib/python3.5/site-packages/torch/nn/modules/module.py", line 180, in add_module
> >     raise KeyError("module name can't contain \".\"")
> > KeyError: 'module name can\'t contain "."'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So I have upgraded torchvision to 0.2.2. and torch==1.1.0. and my train went successful. When I try to run **denseNet_localization.py** file then I got the above error.
> 
> Hello @rajdeinno how did u solve this error please healp me in this regard.
> Thanks @rajdeinno

check this.
https://github.com/thtang/CheXNet-with-localization/issues/7#issuecomment-514562151

**Comment by Aliktk** [comment]
> Hi Tang, I am able to generate the bound_box.txt file after I execute the denseNet_localization.pyfile. how to visualize the bound box text file into the input image? as you mentioned in ground-truth label (red) and its prediction (blue). Thanks in advance.. Please assist me on this..
> […](#)
> Sent from my iPhone
> On 28-May-2019, at 17:57, T.H. Tang ***@***.***> wrote: It seem that the errors are just caused by the different version of packages. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

@rajdeinno  hello sir after generating BB file how you print BB on that image with heatmap of that image?
Pleae help
